version: "3.8"

services:
  app:
    # image: learning-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    restart: always
  db:
    image: mongo
    ports:
      - "27018:27017"
    restart: unless-stopped

